
import java.sql.*;
import java.lang.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JITHIN V J
 */
public class AdminUpdate1 extends javax.swing.JFrame {

    /**
     * Creates new form AdminUpdate1
     */
    public AdminUpdate1() {
        initComponents();
        c1.setVisible(false);
        c2.setVisible(false);
        tf3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        tf3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("UPDATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Age", "Hospital", "MobileNo", "Experience" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FirstName", "Age", "DOB", "Gender", "BloodGroup", "MobileNo", "City" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, -1, -1));

        b1.setText("DOCTOR");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 161, 48));

        b2.setText("PATIENT");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 150, 48));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 355, 39));

        l1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l1.setText("Enter the Name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 182, -1));

        b3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b3.setText("CONFIRM");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 149, 51));
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 46, 184, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter the MailId");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 156, -1));

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 355, 42));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JITHIN V J\\Downloads\\Project Wallpaper\\18.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2250, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

tf3.setText(b1.getText());
c2.setVisible(false);
c1.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
            if(c1.getSelectedItem()=="Hospital")
            {
                    l1.setText("Enter the Hospital");
            }
            else if(c1.getSelectedItem()=="MobileNo")
            {
                l1.setText("Enter the MobileNo");
            }
            else if(c1.getSelectedItem()=="Age")
            {
                l1.setText("Enter the Age");
            }
            else if(c1.getSelectedItem()=="Experience")
            {
                l1.setText("Enter the Expereince");
            }
            else
            {
                l1.setText("Enter the Name");
            }
    }//GEN-LAST:event_c1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
tf3.setText(b2.getText());
c1.setVisible(false);
c2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
             if(c2.getSelectedItem()=="Gender")
            {
                    l1.setText("Enter the Gender");
            }
            else if(c2.getSelectedItem()=="MobileNo")
            {
                l1.setText("Enter the MobileNo");
            }
            else if(c2.getSelectedItem()=="Age")
            {
                l1.setText("Enter the Age");
            }
            else if(c2.getSelectedItem()=="BloodGroup")
            {
                l1.setText("Enter the BloodGroup");
            }
            else if(c2.getSelectedItem()=="City")
            {
                l1.setText("Enter the City");
            }
            else
            {
                l1.setText("Enter the Name");
            }        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        System.out.println(tf3.getText());
        String s=tf3.getText();
        String aa1;
        
        if(s.equals("PATIENT"))
        {
            
        
           try{
    
                   
         Class.forName("com.mysql.cj.jdbc.Driver");
        
         String url="jdbc:mysql://localhost:3306/e_healthcaredb";
            Connection c=java.sql.DriverManager.getConnection(url,"root","");
        System.out.println("No Problem");
        String str="UPDATE patient_signup set "+c2.getSelectedItem()+" = '"+tf1.getText()+"' where EmailId='"+tf2.getText()+"'";
        System.out.println(str);
        Statement stmt= c.createStatement();
        System.out.println(str);
        stmt.executeUpdate(str); 
        
        JOptionPane.showMessageDialog(null,"Updated");
         AdminLogin al=new AdminLogin();
        al.setVisible(true);
        setVisible(false);
        }
           
           catch(Exception e)
           {
                System.out.println(e);
           }
        }
        else 
        {
            System.out.println("OKK");
            try{
    
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        
        String url="jdbc:mysql://localhost:3306/e_healthcaredb";
            Connection c=java.sql.DriverManager.getConnection(url,"root","");
        System.out.println("No Problem");
        String str="UPDATE doctor_signup set "+c1.getSelectedItem()+" = '"+tf1.getText()+"' where EmailId='"+tf2.getText()+"'";
        
        System.out.println(str);
        Statement stmt= c.createStatement();
        System.out.println(str);
        stmt.executeUpdate(str); 
        
        JOptionPane.showMessageDialog(null,"Updated");
         Admin all=new Admin();
        all.setVisible(true);
        setVisible(false);
        }
           
           catch(Exception e)
           {
                System.out.println(e);
           }
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin aa= new Admin();
        aa.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdate1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
