
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class DoctorLogin extends javax.swing.JFrame
{

    /**
     * Creates new form LoginPatient
     */
     public DoctorLogin() {
        initComponents();
        l3.setVisible(false);
        b3.setVisible(false);
        t1.setVisible(false);
        t1.setFocusable(false);
    }
     public boolean LoginDoctormail(String mail)
    {
        final String emailregex = 
        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    Pattern pat=Pattern.compile(emailregex);
    if (mail == null)
            return false;
    return pat.matcher(mail).matches();
 }


    /**
     * Creates new form DoctorLogin
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setText("LOGIN");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 377, 122, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 187, 300, -1));

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 283, 300, -1));

        l1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l1.setText("Gmail Id");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 190, 80, -1));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l2.setText("Password");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 286, 110, -1));

        l4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l4.setText("LOGIN..........");
        l4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        l4.setMaximumSize(new java.awt.Dimension(178, 48));
        l4.setMinimumSize(new java.awt.Dimension(178, 48));
        l4.setPreferredSize(new java.awt.Dimension(178, 48));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 85, 97, 52));

        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 17, -1, -1));

        l3.setText("Invalid Password");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 286, 156, -1));

        b3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        b3.setText("My Appointments");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, 50));

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", "     "
            }
        ));
        t1.setEnabled(false);
        t1.setFocusable(false);
        t1.setOpaque(false);
        t1.setRequestFocusEnabled(false);
        t1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 830, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JITHIN V J\\Downloads\\Project Wallpaper\\4.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2050, 1140));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 830, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed
    String s3,s4; 
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
        s3=tf1.getText();
        s4=p1.getText();
        String query="select * from Doctor_password";
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/e_healthcaredb";
            Connection c=DriverManager.getConnection(url,"root","");
            Statement st=c.createStatement();
        
            ResultSet rs=st.executeQuery(query);
            int flag =0;
            
            while(rs.next())
            {
                if(s3.equals(rs.getString("Email")))
                {
                    flag=1;
                    //String s5=rs.getString("EmailId");
                    // System.out.println(s5);
                    
                        if(s4.equals(rs.getString("Password")))
                        {
                                //JOptionPane.showMessageDialog(null, "Login SuccessFull");
                                l3.setVisible(false);
                                b3.setVisible(true);
                                l1.setVisible(false);
                                l2.setVisible(false);
                                l4.setVisible(false);
                                tf1.setVisible(false);
                                b1.setVisible(false);
                                p1.setVisible(false);
                                
                                
                        }
                        else
                        {
                               String s="";
                               p1.setText(s);
                               
                               l3.setVisible(true);
                        }
                }
               
            }
            
            if(flag==0)
            {
                if(LoginDoctormail(s3))
                {
                    JOptionPane.showMessageDialog(null, "You have not Signed Up this account");
                }
                else{
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Email ID");
            }
            }
        }
        
        catch(Exception e)
        {
          
            System.out.println("Exception"+e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
                setVisible(false);
                Login l=new Login();
                l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String query="select * from doctor_signup ";//where EmailId ='"+tf1.getText()+"'";
        String s = null;
        t1.setVisible(true);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println(query);
            String url="jdbc:mysql://localhost:3306/e_healthcaredb";
            System.out.println("p1");
            Connection c=DriverManager.getConnection(url,"root","");
            Statement st=c.createStatement();
            System.out.println("p2");
            ResultSet rs=st.executeQuery(query);
            System.out.println("p3");
            while(rs.next())
            {
                String s1=rs.getString("EmailId");
                String s2=tf1.getText();
                    if(s1.equals(s2))
                    {
                    s=rs.getString("Name");
                    }
            }
            System.out.println("p4");
                
            
             
             System.out.println(s);
        }
catch(Exception e)
{
    System.out.println(e);
    JOptionPane.showMessageDialog(null,"Probs 1");
}
           try{
            
        String str="select * from appointment where Consulting_Doctor='"+s+"'";
        System.out.println(str);
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/e_healthcaredb","root","");
        Statement stmt= conn.prepareStatement(str);
        ResultSet rs1 = stmt.executeQuery(str); 
       // System.out.println(rs1.getString("Name"));
       // System.out.println("HH"+rs1);
       t1.setVisible(true);
        t1.setModel(DbUtils.resultSetToTableModel(rs1));        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null,"Probs 2");
               System.out.println(e);
           }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField p1;
    private javax.swing.JTable t1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
