
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JITHIN V J
 */
public class LoginPatient extends javax.swing.JFrame {

    /**
     * Creates new form LoginPatient
     */
    String pl;
    public LoginPatient() {
        initComponents();
        
        l3.setVisible(false);               
        
    }
     public boolean LoginPatientmail(String mail)
    {
        final String emailregex = 
        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    Pattern pat=Pattern.compile(emailregex);
    if (mail == null)
            return false;
    return pat.matcher(mail).matches();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        l1.setText("Email");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 176, 108, 40));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 181, 335, -1));

        l2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        l2.setText("LOGIN");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 317, 54));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 292, -1, -1));

        b1.setText("Login");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 33));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 310, -1));

        l3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 51, 0));
        l3.setText("* IncorrectPassword");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 172, -1));

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 286, 235, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\JITHIN V J\\Downloads\\Project Wallpaper\\6.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1100, -450, 3030, 1630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed
       String s3,s4;
       //varChar s7;
       
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         s3=tf1.getText();
        
        System.out.println(s3);
        s4=p1.getText();
        pl=s3;
        String query="select * from Patient_SignUp";
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/e_healthcaredb";
            Connection c=DriverManager.getConnection(url,"root","");
            Statement st=c.createStatement(); 
        
            ResultSet rs=st.executeQuery(query);
            int flag =0;
            
            while(rs.next())
            {
                if(s3.equals(rs.getString("EmailId")))
                {
                    flag=1;
                    //String s5=rs.getString("EmailId");
                    // System.out.println(s5);
                    
                        if(s4.equals(rs.getString("Password")))
                        {
                                //JOptionPane.showMessageDialog(null, "Login SuccessFull");
                                l3.setVisible(false);
                                setVisible(false);
                                PatientPage pp=new PatientPage(s3);
                                final String plz=s3;
                                System.out.println(plz);
                               // PatientPage pp1=new PatientPage(s3);
                                pp.setVisible(true);
                                
                        }
                        else
                        {
                               String s="";
                               p1.setText(s);
                               
                               l3.setVisible(true);
                        }
                }
               
            }
            
            if(flag==0)
            {
                if(LoginPatientmail(s3))
                {
                    JOptionPane.showMessageDialog(null, "You have not Signed Up this account");
                }
                else{
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Email ID");
            }
            }
        }
        
        catch(Exception e)
        {
            
          
            System.out.println("Exception"+e);
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                setVisible(false);
                Login l=new Login();
                l.setVisible(true); 
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
