
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class SignUpDoctor extends javax.swing.JFrame {

    /**
     * Creates new form SignUpDoctor
     */
    public SignUpDoctor() {
        initComponents();
        f1.setVisible(false);
        f2.setVisible(false);
        f3.setVisible(false);
    }
     public boolean SignUpDoctormail(String mail)
    {
        final String emailregex = 
        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    Pattern pat=Pattern.compile(emailregex);
    if (mail == null)
            return false;
    return pat.matcher(mail).matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        c51 = new javax.swing.JComboBox<>();
        l7 = new javax.swing.JLabel();
        c41 = new javax.swing.JComboBox<>();
        l8 = new javax.swing.JLabel();
        tf9 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        c1 = new javax.swing.JCheckBox();
        l3 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        c3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        c4 = new javax.swing.JComboBox<>();
        c5 = new javax.swing.JComboBox<>();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l1.setText("Name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 85, 131, -1));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 82, 120, -1));

        l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l2.setText("Age");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 151, 131, -1));
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 148, 120, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hospital");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 211, 131, 33));

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 212, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Specialization");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 278, 150, 33));

        l5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l5.setText("Working Hours");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 348, 160, -1));

        l6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l6.setText("From");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 351, -1, -1));

        c51.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));
        getContentPane().add(c51, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        l7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l7.setText("To");
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        c41.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));
        getContentPane().add(c41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        l8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l8.setText("Mobile No");
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 131, -1));
        getContentPane().add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 170, -1));

        b1.setText("Confirm");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, 91, -1));

        c1.setText("Accept our terms and condtions");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, -1, -1));

        l3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l3.setText("Create an new account");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 14, 286, 40));

        b3.setText("Back");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulting Physician", "General Physician", "Diabetologist", "Cardiologist", "Orthopaedician", "Gynaecologist", "Dermantalogist", "Neurologist", "Pediatrician", "Psychiatrisit", "General Surgeon", "Nephrologist", "Endocrinologist", "Gastroenteromologist", "Ophthalamologist", "ENT", "Pulmonologist", "Urologist", "Oncologist", "Rheumatologist" }));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Gmailid");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Experience");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });
        getContentPane().add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 170, -1));

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 170, -1));

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "1:30", "2:00", "2:30", "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "1:30", "2:00", "2:30", "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30" }));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        f2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 0, 0));
        f2.setText("*Only 10  digits");
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));

        f3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 0, 0));
        f3.setText("*In valid");
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        f1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 0, 0));
        f1.setText("*All Fields are required");
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\JITHIN V J\\Downloads\\Project Wallpaper\\2.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2080, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    tf1.setText("");
    tf2.setText("");
    tf3.setText("");
    
    tf6.setText("");
    
    p1.setText("");
    tf9.setText("");
    //tf10.setText("");
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
             int len;
         String mob;
        // int aa=c2.getSelectedIndex();
         mob=tf9.getText();
         len=mob.length();
         String s2 = null;
         String ss=tf6.getText();
         try
         {
             
             s2=p1.getText();
             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"Password Field is required");
             System.out.println("Exception"+e);
         }
         System.out.println(s2);
         int flag=1;
         int cnt=0;
         if(flag==1)
         {    
        if (!c1.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Accept the terms and conditions");
        }
        else
        {
            cnt++;
        }
        
        if(!"".equals(tf1.getText())||!"".equals(tf2.getText())||!"".equals(tf9.getText())||!"".equals(tf3.getText())||!"".equals(tf6.getText())||!"".equals(p1.getText())||!"".equals(tf8.getText()));//||!"".equals(Gender())||aa!=0)
        {
        f1.setVisible(false);
        cnt++;
        }

        
        if(!"".equals(tf1.getText())||!"".equals(tf2.getText())||!"".equals(tf9.getText())||!"".equals(tf3.getText())||!"".equals(tf6.getText())||!"".equals(p1.getText())||!"".equals(tf8.getText()));
        {
        f1.setVisible(true);
        }
       
         
         if(SignUpDoctormail(ss))
        {
            f3.setVisible(false);
        }
         
         if(!SignUpDoctormail(ss))
        {
            f3.setVisible(true);
            
        }
         else
         {
             cnt++;
         }
         if(len ==10)
         {
             f2.setVisible(false);
         }
         if(len!=10)
        {
            f2.setVisible(true);
        }
         else
         {
            cnt++;
         }
         }
         String date=tf9.getText();
         

            
           if(cnt==4)
        {
            try
            {
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/e_healthcaredb","root","");
                Statement st=con.createStatement();
                String s1;
                String s3;
                s3=(String) c3.getSelectedItem();
               String str="INSERT INTO Doctor_SignUp values('"+tf1.getText()+"','"+tf2.getText()+"','"+tf3.getText()+"','"+c3.getSelectedItem()+"','"+c5.getSelectedItem()+"','"+c51.getSelectedItem()+"','"+c4.getSelectedItem()+"','"+c41.getSelectedItem()+"','"+tf6.getText()+"','"+tf8.getText()+"','"+tf9.getText()+"')";
               String str1="INSERT INTO Doctor_Password values('"+tf1.getText()+"','"+tf6.getText()+"','"+p1.getText()+"')";//,'"+tf10.getText()+"')";
               st.executeUpdate(str);
                st.executeUpdate(str1);
               DoctorLogin dl=new DoctorLogin();
               setVisible(false);
               dl.setVisible(true);
            }
            catch(SQLException e)
            {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Not Inserted");
            }
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
            
            SignUp s1=new SignUp();
            s1.setVisible(true);
            setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JCheckBox c1;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c41;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c51;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
